# version: '3'
services:
  api:
    build: .
    container_name: instrument_classification-api
    ports:
      - "8000:8000"  # FastAPI
      - "8501:8501"  # Streamlit
    volumes:
      - .:/app
    command: >
      sh -c "uvicorn api.fast_api:app --host 0.0.0.0 --port 8000 &
             streamlit run /app/interface/app.py --server.port=8501 --server.address=0.0.0.0"
